version: "3.9"

services:
  gpujpeg-container:
    image: gpujpeg-container
    container_name: gpujpeg-container
    build:
      context: .
      dockerfile: Dockerfile

    stdin_open: true
    tty: true

    # === GPU access ===
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all   # compute,utility works too

    # === Required to allow nvidia-smi clock/power controls ===
    privileged: true
    cap_add:
      - SYS_ADMIN

    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools

    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
      - ./src:/workspace/src

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]