services:
  mozjpeg-container:
    image: mozjpeg-container
    container_name: mozjpeg-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHANNEL: ${CHANNEL:-stable}
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
