services:
  mozjpeg-container:
    image: mozjpeg-container
    container_name: mozjpeg-container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
      - ./src:/workspace/src
