services:
  libjxl-container:
    image: libjxl-container
    container_name: libjxl-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHANNEL: ${CHANNEL:-stable}
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
