services:
  libavif-container:
    image: libavif-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHANNEL: ${CHANNEL:-stable}
    container_name: libavif-container
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
    command: ["/usr/local/bin/build_project.sh"]
