services:
  jpegli-container:
    image: jpegli-container
    container_name: jpegli-container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
      - ./src:/workspace/src
