services:
  libwebp-container:
    image: libwebp-container
    container_name: libwebp-container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset