services:
  libavif-svt-container:
    image: libavif-svt-container
    container_name: libavif-svt-container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
      - ./src:/workspace/src
