services:
  libjpeg-turbo-container:
    image: libjpeg-turbo-container
    container_name: libjpeg-turbo-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHANNEL: ${CHANNEL:-stable}
    stdin_open: true
    tty: true
    volumes:
      - ./results:/workspace/results
      - ./imageset:/workspace/imageset
